# Generated by Django 4.0 on 2021-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_token', models.CharField(max_length=256, verbose_name='NFT')),
                ('user_id', models.CharField(max_length=128, verbose_name='User id')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('price', models.FloatField(verbose_name='Price')),
                ('active', models.BooleanField(verbose_name='Is active')),
            ],
        ),
    ]
